import type { CSSProperties } from "react";
import {
  Activity,
  Braces,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  CircleDot,
  Code2,
  Copy,
  Database,
  Download,
  Eraser,
  Files,
  Filter,
  Folder,
  FolderOpen,
  Gauge,
  GitBranch,
  Globe,
  Hash,
  History,
  Info,
  Key,
  Keyboard,
  Layers,
  List,
  ListOrdered,
  Minimize2,
  Moon,
  MoreHorizontal,
  PanelLeft,
  PanelRight,
  Pause,
  Pencil,
  Play,
  Plug,
  Plus,
  Radio,
  RefreshCw,
  Rows3,
  Save,
  Search,
  Send,
  Settings2,
  Sparkles,
  Sun,
  Table2,
  Terminal,
  Timer,
  Trash2,
  Users,
  Waves,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICONS = {
  activity: Activity,
  "arrow-left": ChevronLeft,
  "arrow-right": ChevronRight,
  braces: Braces,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  "chevrons-down": ChevronsDown,
  "chevrons-left": ChevronsLeft,
  "chevrons-right": ChevronsRight,
  "chevrons-up": ChevronsUp,
  cluster: Activity,
  code: Code2,
  copy: Copy,
  database: Database,
  docs: Files,
  download: Download,
  eraser: Eraser,
  filter: Filter,
  folder: Folder,
  "folder-open": FolderOpen,
  gauge: Gauge,
  github: GitBranch,
  globe: Globe,
  groups: Users,
  hash: Hash,
  history: History,
  info: Info,
  key: Key,
  keyboard: Keyboard,
  layers: Layers,
  list: List,
  "list-ordered": ListOrdered,
  minify: Minimize2,
  moon: Moon,
  "more-horizontal": MoreHorizontal,
  "panel-left": PanelLeft,
  "panel-right": PanelRight,
  pause: Pause,
  pencil: Pencil,
  play: Play,
  plug: Plug,
  plus: Plus,
  radio: Radio,
  refresh: RefreshCw,
  rows: Rows3,
  save: Save,
  search: Search,
  send: Send,
  settings: Settings2,
  sparkles: Sparkles,
  status: CircleDot,
  stream: Waves,
  sun: Sun,
  table: Table2,
  terminal: Terminal,
  timer: Timer,
  topics: Layers,
  trash: Trash2,
  x: X,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

interface Props {
  name: IconName;
  size?: number;
  style?: CSSProperties;
  className?: string;
}

export function Icon({ name, size = 15, style, className }: Props) {
  const Component = ICONS[name];
  return <Component size={size} strokeWidth={1.8} style={{ flex: "none", ...style }} className={className} aria-hidden />;
}
